apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-api.fullname" . }}
  labels:
    {{- include "job-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "job-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "job-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "job-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: job-api
        - name: gatekeeper-sidecar
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: keycloak/keycloak-gatekeeper
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-gatekeeper
              containerPort: 3000
              protocol: TCP
          args:
            - --discovery-url={{ .Values.keycloak.url }}
            - --client-id={{ .Values.keycloak.clientId }}
            - --listen=0.0.0.0:3000
            - --upstream-url=http://127.0.0.1:8080
            - --secure-cookie=false
          env:
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: job-api-gatekeeper-secret
                key: client-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
